# permissions for end users to view virtualmobilephones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmobilephone-viewer-role
rules:
- apiGroups:
  - infra.qiuwenqi.com
  resources:
  - virtualmobilephones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.qiuwenqi.com
  resources:
  - virtualmobilephones/status
  verbs:
  - get
