# permissions for end users to edit virtualmobilephones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmobilephone-editor-role
rules:
- apiGroups:
  - infra.qiuwenqi.com
  resources:
  - virtualmobilephones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.qiuwenqi.com
  resources:
  - virtualmobilephones/status
  verbs:
  - get
